import { definePageMetadata } from "../../../packages/makit/src/metadata/index.ts";

export default definePageMetadata({
  id: "guides.deployment",
  title: "Deployment",
  description: "Publish a static site generated by Makit.",
});
