export { defineConfig } from "./config/define-config.js";
export type {
  DeploymentConfig,
  DeploymentConfigFileMode,
  GeneratedHeaderRule,
  GeneratedRedirect,
} from "./types/adapter.js";
export type {
  BuildConfig,
  AnalyticsConfig,
  AnalyticsScriptConfig,
  AnalyticsScriptStrategy,
  CodeBlockConfig,
  DevConfig,
  ExperimentalConfig,
  ExternalLinksConfig,
  FooterConfig,
  FooterLink,
  GoogleAnalyticsConfig,
  GoogleTagManagerConfig,
  HeaderConfig,
  HeaderLink,
  MakitColorScheme,
  MakitConfig,
  MakitFallbackBehavior,
  MakitI18nConfig,
  LlmsConfig,
  MakitLocaleConfig,
  MakitLocaleFallbackConfig,
  MakitMessages,
  MakitMissingPageBehavior,
  MakitRadius,
  MakitRootBehavior,
  MakitWarningCode,
  MarkdownConfig,
  NavigationConfig,
  NavigationGroup,
  NavigationItem,
  NavigationMode,
  PreviewConfig,
  PostHogConfig,
  SeoConfig,
  ShikiConfig,
  ShikiDualTheme,
  ShikiUnknownLanguageBehavior,
  SitemapConfig,
  TableOfContentsConfig,
  ThemeConfig,
  UmamiConfig,
  ValidationConfig,
  VercelWebAnalyticsConfig,
} from "./types/config.js";
