export { defineConfig } from "./config/define-config.js";
export type {
  BuildConfig,
  CodeBlockConfig,
  DevConfig,
  ExperimentalConfig,
  ExternalLinksConfig,
  FooterConfig,
  FooterLink,
  HeaderConfig,
  HeaderLink,
  MakitColorScheme,
  MakitConfig,
  MakitFallbackBehavior,
  MakitI18nConfig,
  MakitLocaleConfig,
  MakitLocaleFallbackConfig,
  MakitMessages,
  MakitMissingPageBehavior,
  MakitRadius,
  MakitRootBehavior,
  MakitWarningCode,
  MarkdownConfig,
  NavigationConfig,
  NavigationGroup,
  NavigationItem,
  NavigationMode,
  PreviewConfig,
  SeoConfig,
  ShikiConfig,
  ShikiDualTheme,
  ShikiUnknownLanguageBehavior,
  SitemapConfig,
  TableOfContentsConfig,
  ThemeConfig,
  ValidationConfig,
} from "./types/config.js";
